import {NgModule} from "@angular/core";
import { SchoolAccessDirective } from "../../directives/school-access/school-access.directive";
import { CommonModule } from "@angular/common";
import {
	GuineaPrimarySchoolComponent,
	GuineaSchoolComponent,
	GuineaSecondarySchoolComponent,
	IgcseSchoolComponent,
	IvoryCoastPrimarySchoolComponent,
	IvoryCoastSchoolComponent,
	IvoryCoastSecondarySchoolComponent,
	KcpeSchoolComponent,
	KcseSchoolComponent,
	KenyanSchoolComponent,
	SouthAfricaPrimarySchoolComponent,
	SouthAfricaSchoolComponent,
	SouthAfricaSecondarySchoolComponent,
	ZambiaPrimarySchoolComponent,
	ZambiaSecondarySchoolComponent,
	ZambiaSchoolComponent,
	TanzaniaPrimarySchoolComponent,
	TanzaniaSchoolComponent,
	TanzaniaSecondarySchoolComponent,
	UgandaSchoolComponent,
	ZimbabweIGCSESchoolComponent,
	ZimbabwePrimarySchoolComponent,
	ZimbabweSchoolComponent,
	ZimbabweSecondarySchoolComponent,
	GhanaPrimarySchoolComponent,
	GhanaPrimaryJuniorSchoolComponent,
	GhanaJuniorSchoolComponent,
	GhanaSeniorSchoolComponent,
	GhanaSchoolComponent,
} from "./index";

@NgModule({
	declarations: [
		KenyanSchoolComponent,
		KcpeSchoolComponent,
		KcseSchoolComponent,
		IgcseSchoolComponent,
		GuineaSchoolComponent,
		GuineaPrimarySchoolComponent,
		GuineaSecondarySchoolComponent,
		UgandaSchoolComponent,
		IvoryCoastSchoolComponent,
		IvoryCoastSecondarySchoolComponent,
		IvoryCoastPrimarySchoolComponent,
		TanzaniaSchoolComponent,
		TanzaniaPrimarySchoolComponent,
		TanzaniaSecondarySchoolComponent,
		ZimbabweSchoolComponent,
		ZimbabwePrimarySchoolComponent,
		ZimbabweSecondarySchoolComponent,
		SouthAfricaSchoolComponent,
		SouthAfricaPrimarySchoolComponent,
		SouthAfricaSecondarySchoolComponent,
		ZambiaPrimarySchoolComponent,
		ZambiaSecondarySchoolComponent,
		ZambiaSchoolComponent,
		ZimbabweIGCSESchoolComponent,
		GhanaPrimarySchoolComponent,
		GhanaPrimaryJuniorSchoolComponent,
		GhanaJuniorSchoolComponent,
		GhanaSeniorSchoolComponent,
		GhanaSchoolComponent,
		SchoolAccessDirective,
	],
	imports: [
		CommonModule
	],
	exports: [
		KcseSchoolComponent,
		KenyanSchoolComponent,
		IgcseSchoolComponent,
		GuineaSchoolComponent,
		UgandaSchoolComponent,
		IvoryCoastSchoolComponent,
		IvoryCoastSecondarySchoolComponent,
		IvoryCoastPrimarySchoolComponent,
		TanzaniaSchoolComponent,
		TanzaniaSecondarySchoolComponent,
		GuineaSecondarySchoolComponent,
		TanzaniaPrimarySchoolComponent,
		GuineaPrimarySchoolComponent,
		SchoolAccessDirective,
		ZimbabweSchoolComponent,
		SouthAfricaSchoolComponent,
		SouthAfricaPrimarySchoolComponent,
		SouthAfricaSecondarySchoolComponent,
		ZambiaPrimarySchoolComponent,
		ZambiaSecondarySchoolComponent,
		ZambiaSchoolComponent,
		GhanaPrimarySchoolComponent,
		GhanaPrimaryJuniorSchoolComponent,
		GhanaJuniorSchoolComponent,
		GhanaSeniorSchoolComponent,
		GhanaSchoolComponent,
	]
})
export class CountryViewsModule {}
