export { StudentsComponent } from "./students.component";
export { MoveStudentComponent } from "./move-student/move-student.component";
export { NewStudentComponent } from "./new-student/new-student.component";
export { SearchStudentComponent } from "./search-student/search-student.component";
export { UpdatePhotoComponent } from "./update-photo/update-photo.component";
export { UpdateProfileComponent } from "./update-profile/update-profile.component";
export { UploadFeeComponent } from "./upload-fee/upload-fee.component";
export { UploadTargetComponent } from "./upload-target/upload-target.component";
export { StudentsTopNavComponent } from "./@components/students-top-nav/students-top-nav.component";
export { StudentProfileComponent } from "./student-profile/student-profile.component";
export { DisciplineComponent } from "./discipline/discipline.component";
export { StudentActivitiesComponent } from "./student-activities/student-activities.component";
export { StudentMessagesComponent } from "./student-messages/student-messages.component";
export { StudentAnalyticsComponent } from "./student-analytics/student-analytics.component";
export * from "./student-residences";
